### ISSUE TITLE
Find Client ID

### ISSUE THREAD

**Issue by iamShantanu101** [RexChenjq/AWS-Image-Backup#2]
Hello, 

There is a mention of tagging AMIs with Client IDs but there is no mention on how to get them.
Can you please give an idea about that? I am facing issues in tagging images with Client IDs.

This is the code I am using:
`import boto3
import collections
import datetime
import sys
import pprint

ec = boto3.client('ec2')
retention_days = 7
def lambda_handler(event, context):

    reservations = ec.describe_instances(
        Filters=[
            {'Name': 'tag-key', 'Values': ['backup', 'Backup', 'Client']},
        ]
    ).get(
        'Reservations', []
    )
    print (reservations)
    instances = sum(
        [
            [i for i in r['Instances']]
            for r in reservations

        ], [])
        
    print "Found %d instances that need backing up" % len(instances)

    to_tag = collections.defaultdict(list)
        
    for instance in instances:
            name_tag = [
                str(t.get('Value')) for t in instance['Tags']
                if t['Key'] == 'Name'][0]
            print (name_tag)
            print ("check_loop")
            
            create_time = datetime.datetime.now()
            create_fmt = create_time.strftime('%Y-%m-%d')

            AMIid = ec.create_image(InstanceId=instance['InstanceId'], Name="Lambda12 - " + instance['InstanceId'] + " " + name_tag +" from " + create_fmt, Description="Lambda created AMI of instance " + instance['InstanceId'] + " " + name_tag + " from " + create_fmt, NoReboot=True, DryRun=False)
            to_tag[retention_days].append(AMIid['ImageId'])

            delete_date = datetime.date.today() + datetime.timedelta(days=retention_days)
            delete_fmt = delete_date.strftime('%m-%d-%Y')
            
            
            instancename = ''
            for tags in instance["Tags"]:
                if tags["Key"] == 'Client':
                    print ("This is instance inside if with key" + tags["Key"])
                    instancename = tags["Value"]
                    print ("This is instancename" + instancename )
                    ec.create_tags (
                        DryRun=False,
                        Resources=to_tag[retention_days],
                        Tags=[
                              {'Key': 'Client', 'Value': instancename},
                        ]
                    )
                print "This is last instancename" + instancename

            ec.create_tags(
                Resources=to_tag[retention_days],
                Tags=[
                        {'Key': 'DeleteOn', 'Value': delete_fmt},
                    ]
            )
              
   
            print ("Name tag " + name_tag)
            print ("check_loopend")
`

However I am finding issues while trying this: `{'Key': 'Client', 'Value': instancename}`
Somehow all the AMIs are getting tagged by same instancename i.e the last one in the loop. Is there anything wrong in the code?

**Comment by RexChenjq** [comment]
You can customise your client ID by yourself. It is used for billing purposes.

You have to take care of for loop. Check if you count 4 spaces correctly.
